require:
- rubocop
- rubocop-rails
- rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
  - bin/**/*
  - db/**/*
  - config/**/*
  - log/**/*
  - public/**/*
  - tmp/**/*
  - Rakefile
  - vendor/**/*
RSpec:
  Patterns:
  - '^spec.*\*\.rb'

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: true
  Include:
  - '**/*.rb'
  IgnoredMethods:
  - render
  - require
  - require_dependency
  - raise
  - head
  - redirect_to
  - respond_to
  - include
  - to
  - not_to
  - to_not
  - describe
  - shared_examples

Layout/LineLength:
  Max: 180
Metrics/ClassLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
  - 'config/routes.rb'
  - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 10
Metrics/AbcSize:
  Max: 25
Lint/MissingSuper:
  Enabled: true
RSpec/MultipleExpectations:
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Style/Documentation:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ExampleLength:
  Max: 20