mongodb:
  url: mongodb://localhost:27017/reports_service_development

quickbooks:
  client_id: "Q0U11mAOqtyrGFVjEtGztoHESET22lFqfcIbgrQQDVVtjBb0di"
  client_secret: "rP5xCEMmGPfx0R7rFyHfkoKq1QFAG8VU0nmfTvIq"
  redirect_uri: "https://app.localhost.docyt.com/cloud_service_authorizations/qbo_oauth_callback"
  api_base_uri: "https://sandbox-quickbooks.api.intuit.com/v3/company"
  client_webhook_token: "2771afa0-eb7d-4d89-9a4b-1b41aa98c130"

redis:
  host: localhost:6379
